### ISSUE TITLE
All content after a section called "Terms and definition" is given the second time

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#33]
```

== Terms and definitions
...

(1)
== Data elements

=== Hello
... 
=== Terms and definitions

```
Then everything after (1) will disappear.

**Comment by opoudjis** [comment]
Terms and definitions sections are detected by the title. If you repeat the title elsewhere, of course bad things are going to happen. The difference in Section depth should have prevented this, I will investigate.

**Comment by ronaldtse** [comment]
Exactly about the section depth, and perhaps only the first detected special section should be special.

**Comment by opoudjis** [comment]
Fixed in metanorma-standoc
