### ISSUE TITLE
Errors when compiling CSD document (used to work before)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#35]
```
The asciidoctor-csd gem has been deprecated and has been replaced by metanorma-csd
...
bundler: failed to load command: metanorma (/Users/myself/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bin/metanorma)
ArgumentError: unknown keyword: affilation
/Users/myself/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/iso-bib-item-0.2.5/lib/iso_bib_item/person.rb:91:in `initialize'
```

**Comment by opoudjis** [comment]
Not able to replicate the error. I'll publish the gem chain from iso-bib-item up.

**Comment by opoudjis** [comment]
The gems were already published, and "affiliation" occurs in the published iso-bib-item-0.2.5. I do not understand how you are getting this error.

**Comment by opoudjis** [comment]
... But the error is occurring in Travis. OK, continuing with this.

**Comment by opoudjis** [comment]
Appears to be because I hadn't pushed rfcbib gem. Waiting on Travis to run.

**Comment by opoudjis** [comment]
Works now. I think this is ok.

**Comment by ronaldtse** [comment]
@opoudjis it seems that this is still shown?

```
The asciidoctor-csd gem has been deprecated and has been replaced by metanorma-csd
```

Is this issue with `metanorma-cli`?

**Comment by opoudjis** [comment]
No, it was an issue with csd; I'd erroneously left the warning in the gem initialisation.
