### ISSUE TITLE
Errors on datetime-explicit document

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#36]
I'm getting this error on the document (admittedly there are errors within the document, but the toolchain should still not fail):

```
NoMethodError: undefined method `[]' for nil:NilClass
  /Users/myself/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/isodoc-0.8.10/lib/isodoc/function/terms.rb:46:in `block (2 levels) in termnote_parse'
```

**Comment by ronaldtse** [comment]
This is caused by a NOTE inside a list item entry:

```adoc
"`M`"::
the months or minutes designator, represented by the character "`M`", preceding a data element which represents the number of months or minutes in a duration expression
+
NOTE: Although "`M`" can be used to designate months or for minutes, its meaning is unambiguous in expressions because the time portion will be preceded by the time designator "`T`".
```

**Comment by opoudjis** [comment]
The cross-references generator for term notes expects to find notes only at the top level of term content, and not embedded in other objects such as lists. (In fact, it doesn't expect to find lists in there either.) This is taking liberties with the CSD grammar. But it should still make an effort to deal with such embedded notes, so I will look for termnotes at an arbitrary level of embedding, using ".//note".

**Comment by ronaldtse** [comment]
Indeed. How does ISO DIR 2 deal with these? Thanks!

**Comment by opoudjis** [comment]
The point is that ISO DIR 2 doesn't deal with them: it does not foresee notes embedded in lists. 

>24.3 Numbering and subdivision
>Within a given clause or subclause, notes shall be numbered sequentially. The numbering restarts at each new subdivision. A single note in a subdivision need not be numbered.

Which implies that the behaviour that (accidentally) happens right now in generic notes is correct: notes are numbered sequentially whether they are inside of lists or examples or paragraphs (but not tables!)

In fact, I've just noticed that p. 19 of the 2016 IEC/ISO DIR 2 *does* have notes embedded in lists, and numbers them sequentially. I'll check the grammar about making sure they're permitted.

**Comment by opoudjis** [comment]
Fixed in isodoc: made termnote_anchor_names, which gives IDs to all termnotes, search for notes as descendants of terms, not just children.
