### ISSUE TITLE
Citations using ISO documents displayed without prefix

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#38]
Code:

```adoc
[bibliography]
== Normative References

* [[[iso8601,ISO 8601:2004]]], _Date and time -- Representation for information interchange_
```

Rendered as:

![screen shot 2018-08-29 at 12 12 07 pm](https://user-images.githubusercontent.com/11865/44764969-f2a91480-ab84-11e8-8216-54682fb249b1.png)

(Should be "ISO 8601:2004" instead of "8601:2004")

**Comment by opoudjis** [comment]
Can't replicate. 

````
      <div>
        <h1 class="Section3">Bibliography</h1>
        <p id="ISOIEC646" class="Biblio">[1]&#xA0; ISO/IEC 646, <i> Information technology -- ISO 7-bit coded character set for information interchange</i></p>
        <p id="ISO80000-1" class="Biblio">[2]&#xA0; ISO 80000-1, <i> Quantities and units -- Part 1: General</i></p>
        <p id="ISO80000-3" class="Biblio">[3]&#xA0; ISO 80000-3, <i> Quantities and units -- Part 3: Space and time</i></p>
        <p id="ISO8601-1" class="Biblio">[4]&#xA0; ISO 8601-1, Date and time&#x2009;&#x2014;&#x2009;Representation for information interchange&#x2009;&#x2014;&#x2009;Part 1: Basic rules</p>
        <p id="ISO8601-2" class="Biblio">[5]&#xA0; ISO 8601-2, Date and time&#x2009;&#x2014;&#x2009;Representation for information interchange&#x2009;&#x2014;&#x2009;Part 2: Extensions</p>
        <p id="IEV" class="Biblio">[6]&#xA0; IEC Electropedia,
    <i>IEC Electropedia</i>
````

I'm not happy to suggest this, because it shouldn't be necessary, but try deleting the caches, both local (if present) and global. The change to prefixes being included in iso-bib-item references is recent.

**Comment by ronaldtse** [comment]
I've tried removing the caches but it still doesn't work...  See the git repo for datetime-explicit and general-recurrence documents?

**Comment by opoudjis** [comment]
I still cannot replicate this.

The change in relaton/isobib/iso-bib-item, which now includes the prefix in the document identifier, has clearly not propagated to you. Doing bundle pristine, in case there are any fixes I haven't published the gems for.

**Comment by opoudjis** [comment]
I think I've found the issue; I had not published the isobib gem update, not to add the ISO prefix twice.

This I'm afraid is an ongoing issue: I am delaying pushing gems so I can push them all together, and thereby not disrupt external users; but if I'm doing fixes for standards you are working on, that means inconsistency. The way forward is going to have to be that you add to your gemfile, to pull from Github, not just the metanorma-* gems, but also the relaton gems.

**Comment by opoudjis** [comment]
Published all gem updates, bundle pristine then bundle update, works my side.
