### ISSUE TITLE
List style shifted out of bounds in HTML (and PDF)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#45]
See picture.

![screen shot 2018-09-03 at 10 06 05 am](https://user-images.githubusercontent.com/11865/44964097-522a6a00-af61-11e8-8749-024aef3fe5be.png)

**Comment by opoudjis** [comment]
Ensured both ul and ol have same indentation, in CSAND, CSD, M3D.

**Comment by ronaldtse** [comment]
Thank you!
