### ISSUE TITLE
Word: Header 2 style missing

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#46]
Pictures.

Appendix:
![screen shot 2018-09-03 at 10 07 33 am](https://user-images.githubusercontent.com/11865/44964122-6a9a8480-af61-11e8-9f16-c5bc9a7bc29c.png)

Terms:
![screen shot 2018-09-03 at 10 07 06 am](https://user-images.githubusercontent.com/11865/44964123-6a9a8480-af61-11e8-84ee-c6673404ad03.png)

Introduction:
![screen shot 2018-09-03 at 10 06 40 am](https://user-images.githubusercontent.com/11865/44964124-6a9a8480-af61-11e8-9084-ce728b4bdc6a.png)

**Comment by opoudjis** [comment]
Introduction, Appendix: .h2Annex style for wordstyle.css had been deleted from all instances but GB. Restored. 

Terms, TermNum: styles had been deleted from secondary stylesheet from all instances but GB, ISO, M3D. Restored.

**Comment by ronaldtse** [comment]
Thanks Nick!

**Comment by ronaldtse** [comment]
Reopened. `h2annex`, `termnum` and `term` are still unstyled (the style is applied, but looks like normal text) in CSD Word.

**Comment by ronaldtse** [comment]
Oops... this is actually fixed. Thanks!
