### ISSUE TITLE
Word: list items placed out of bounds on left

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#47]
Unnumbered list:
![screen shot 2018-09-03 at 10 06 56 am](https://user-images.githubusercontent.com/11865/44964163-97e73280-af61-11e8-8fd8-88c95b1e2c8f.png)

Numbered list:
![screen shot 2018-09-03 at 10 07 15 am](https://user-images.githubusercontent.com/11865/44964164-987fc900-af61-11e8-8865-1ec7b13ae66b.png)

**Comment by opoudjis** [comment]
All secondary Word stylesheets but ISO, M3D, GB had been altered with override to left-flush lists; fixed.

**Comment by ronaldtse** [comment]
Thank you!

**Comment by ronaldtse** [comment]
@opoudjis this is not fixed, reopened.

`h2annex`, `termnum` and `term` are still unstyled (the style is applied, but looks like normal text) in CSD Word.

**Comment by ronaldtse** [comment]
HTML/PDF: `lowerroman` lists like a), b) are out of bounds, unnumbered lists are fine.

Word: unnumbered lists and lowerroman lists both out of bounds.

**Comment by ronaldtse** [comment]
Oops... this is actually fixed. Thanks!
