### ISSUE TITLE
Extra page after cover page

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#49]
This is an empty full page after the cover page.

Picture:

![screen shot 2018-09-05 at 1 41 08 pm](https://user-images.githubusercontent.com/11865/45073326-6c0aaf00-b111-11e8-8f56-6c70662e4c03.png)

**Comment by ronaldtse** [comment]
Yes, we want it. However is it not rendered correctly?

**Comment by opoudjis** [comment]
I can close the box, just need more text than just `©2018.`

**Comment by ronaldtse** [comment]
I think we're miscommunicating.

HTML version is fine:

![screen shot 2018-09-05 at 10 56 36 pm](https://user-images.githubusercontent.com/11865/45101909-13620300-b15f-11e8-9542-b2748ac43405.png)

Word version has the latter part missing:

![screen shot 2018-09-05 at 10 56 49 pm](https://user-images.githubusercontent.com/11865/45101916-15c45d00-b15f-11e8-8188-dd26ee0ed246.png)
