### ISSUE TITLE
Accept multiple committees 

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#52]
As title.

e.g., "TC VCARD, TC CALENDAR" rather than currently "TC VCARD, CALENDAR" when I put "VCARD, CALENDAR" in the `:technical-committee:` document attribute.

**Comment by opoudjis** [comment]
Isn't this going to apply to all Metanorma documents? If so, it will mean a grammar change.

**Comment by ronaldtse** [comment]
Yes please. We should support multiple authorships, whether individuals or committees or organizations.

**Comment by ronaldtse** [comment]
But doesn’t already the Relaton model support this?

**Comment by opoudjis** [comment]
No, this is only in standards-specific extensions of Relaton, and it has only ever licensed one committee. I am allowing more than one for CSD; you need to tell me if more than one applies to other standards as well, including ISO and GB.

**Comment by opoudjis** [comment]
.... Don't use split on the technical-committee document attribute, because you have technical-committee-type as well. The solution should instead be the same as Asciidoctor does for multiple authors: technical-committee, technical-committee-type, technical-committee2, technical-committee-type2, technical-committee3, technical-committee-type3...

**Comment by ronaldtse** [comment]
I think we should allow more than one committee (i.e. contributor = author) for the standards. The solution would be fine. This aligns us with AsciiRFC too where multiple authors are supported.

**Comment by opoudjis** [comment]
Implemented for CSD. Will roll out for other standards, other than ISO, GB.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !

**Comment by opoudjis** [comment]
Done in all gems, including ISO.
