### ISSUE TITLE
Style a CSD manifest

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-csd#55]
In https://github.com/riboseinc/metanorma-mpfd/issues/1, Pierre, you created a stylesheet for a manifest of external references to files.

I have created a script that renders manifests as normal ISO XML documents, and converts those to HTML. The manifests are meant to be just like normal standards documents, with their components as normal clauses and subclauses; so modifying the contents of the HTML file is not a desirable option; we want this file to look like an index of other files, but altering only the CSS, while still preserving the look-and-feel of normal CSD documents.

I am attaching where I have gotten to, along with the input file from which it is generated (in YAML). The task is to change the CSS to something more like what @ronaldtse wants, for an index of CSD documents. The problem is that I'm somewhat vague as to what he wants, and you will have to liaise with him as to specifics.

[csd index.zip](https://github.com/riboseinc/metanorma-csd/files/2405464/csd.index.zip)

**Comment by ronaldtse** [comment]
@pierrefortier the point is to get an index page for CSD documents, so the ToC / Foreword etc is not quite desired.

There are actually two hierarchical representations we wanted:

1. Index page of documents. There's no Foreword etc. Each document is independent, shows the document identifier (e.g. 'RFC 1234') and document title of each document, possibly also the publication date / last updated date of each, and indicating the document status (draft, published).

Example:
https://www.iso.org/committee/53186/x/catalogue/p/1/u/0/w/0/d/0


2. Hierarchical site. It is a linked site of documents (i.e. 1 large document split into smaller documents). Each document may have a different publication date. The landing page of the site is a document itself. A single ToC for the whole site.

Example:
https://alphagov.github.io/digitalmarketplace-manual/

(In the example it doesn't show the publication date of individual pages, but we will need to show them).

**Comment by pierrefortier** [comment]
Hello,

Here's my first stab at the index page (#1 in @ronaldtse 's comment).

I did have to add some html to take in to account some new elements (doc identifier, doc stage, publication and update dates for each document) but otherwise it's the same structure with only CSS modifications. 

@opoudjis let me know if this works for you.

[csd-manifest-index.zip](https://github.com/riboseinc/metanorma-csd/files/2407949/csd-manifest-index.zip)

**Comment by pierrefortier** [comment]
Sure thing, here is an update.
[csd-manifest-index 2.zip](https://github.com/riboseinc/metanorma-csd/files/2407995/csd-manifest-index.2.zip)

**Comment by ronaldtse** [comment]
@pierrefortier could we also reuse the color pallet from the CSD document, i.e. if something is published it shows a "green" status, etc?

Is there something you can do to make the page prettier? 😉

To make this as realistic as possible, could you:
* add the CalConnect logo to it?
* See any hints from an existing page: https://devguide.calconnect.org/
* The copyright statement in the previous version (was in the header) should be moved to the bottom.

Thanks!

**Comment by pierrefortier** [comment]
Sure, here's another update.

[csd-manifest-index 3.zip](https://github.com/riboseinc/metanorma-csd/files/2408078/csd-manifest-index.3.zip)

**Comment by ronaldtse** [comment]
Thanks @pierrefortier !

Could we have the following changes too?

* Document identifier (code) and document title on different lines (and at the same font size)
(https://www.iso.org/committee/53186/x/catalogue/p/1/u/0/w/0/d/0 does that)

* Differentiate "document type" (standard, guide, directive/governance, report) and "document stage" (proposal, working draft, committee draft, published, withdrawn, cancelled). Each document will have both of these elements.

* A bit of a tighter layout (less row padding, like the ISO one)

* Responsive layout so it reads on mobile

Nice-to-have enhancement:

* Make the list sortable via JS (document code, publication date, document type, document stage)

Thanks!

**Comment by pierrefortier** [comment]
Here are my updates.

[csd-manifest-index 4.zip](https://github.com/riboseinc/metanorma-csd/files/2408872/csd-manifest-index.4.zip)

**Comment by pierrefortier** [comment]
Updated.

[csd-manifest-index 5.zip](https://github.com/riboseinc/metanorma-csd/files/2410535/csd-manifest-index.5.zip)

**Comment by opoudjis** [comment]
Thank you. We've made a change of direction, and are now generating the HTML from Relaton XML instead of via Metanorma, since Metanorma simply does not have the semantic richness to provide those document classes. Will be using the CSS you have provided, as modified by Ronald.

**Comment by ronaldtse** [comment]
Thanks guys, I’ve actually put the document and updated CSS at https://github.com/riboseinc/csd-style, and it’s up at www.calendarstandards.org 

:-)
