### ISSUE TITLE
relaton for Calconnect

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-csd#56]
Yes, we need a "data index" that points to all the documents. This is a static document -- a generated "index file".

We want a "static" API, so only providing access to structured data. We don't need to do searches.

**Comment by opoudjis** [comment]
I simply don't know what to do here. I'm not in a position to set up a web service without data to talk to. If there is a single master index of CSD documents, then I guess an API can talk to it; but what is this index? A YAML file? A text file? What API is exposed? A paged list of all documents from the one service call? A numeric iteration of documents?

**Comment by ronaldtse** [comment]
We are in position to decide what this data is and where it lives. I am still most attracted to a static data site (a “non dynamic web service”). 

Let’s think of it as a “standard document” index service. We need the “index” and for each document the “bibinfo” data. The “BibItem” data can be in Relaton XML. 

This works, right?

**Comment by ronaldtse** [comment]
At an ISO TC, their "standards catalog" has these elements:


Standard and/or project under the direct responsibility of ISO/TC 46/SC 9 Secretariat (32) | Stage | ICS
-- | -- | --
ISO 4:1997Information and documentation -- Rules for the abbreviation of title words and titles of publications | 90.93 | 01.140.40
ISO 690:2010Information and documentation -- Guidelines for bibliographic references and citations to information resources | 90.92 | 01.140.20
ISO/WD 690 [Under development]Information and documentation -- Guidelines for bibliographic references and citations to information resources | 20.20 | 01.140.20
ISO 832:1994Information and documentation -- Bibliographic description and references -- Rules for the abbreviation of bibliographic terms | 90.93 | 01.140.20

...

And you can filter by:
* State: Published; Under development; Withdrawn; Deleted
* Text (free text)

**Comment by opoudjis** [comment]
OK, so:

* sinatra web server
* static index of bibdata entries for all standards in YAML
* script to convert those YAML files into Relaton XML files (A)
* script to convert those YAML files into one big YAML index file (B)
* GET relaton-server-csd : returns list of all specs with tc, id, title, stage, pub date (JSON file, generated via YAML at B)
* GET relaton-server-csd/id/DocID : returns bibdata of individual spec (generated at A)

I will create a gem, the scripts, and a dummy set of YAML files. If you could point me to an existing list of Calconnect standards, so my data can be realistic, that would be good.

**Comment by opoudjis** [comment]
https://github.com/riboseinc/relaton-server-csd

**Comment by opoudjis** [comment]
The scope appears to be the documents created by technical committees in https://www.calconnect.org/resources/documents/document-register , except that they all seem to be IETF drafts. I'll grab the latest three and make them the basis of the test data.

**Comment by ronaldtse** [comment]
Instead of a dynamic server, can we just start with a set of Jekyll pages?

**Comment by opoudjis** [comment]
... you mean, a static page generated for each endpoint? Ok, I guess, I'll just need to read up on Jekyll. (I had once, but have forgotten all about it.)

**Comment by ronaldtse** [comment]
Exactly. A static site with results pre-generated. Thanks!

**Comment by opoudjis** [comment]
This is the  first cut output. I have not worked out how to Jekyll it yet, so these are just HTML files, containing JSON and Relaton XML respectively. I am attaching the output (data/out), and the input YAML file (data/repo/index.yaml) — which is in the same format that the manifest processor accepts. Let me know if this is what you are after, and I will proceed with Jekyll.

[data.zip](https://github.com/riboseinc/metanorma-csd/files/2413289/data.zip)

**Comment by ronaldtse** [comment]
@opoudjis This is exactly what I wanted. That said, we should be consistent in using XML vs JSON, either they should all be in Relaton XML, or all in Relaton JSON (yes there should be something like this!) (or both!).

e.g.
```
/xml/index.xml
/xml/cd-0403.xml
/xml/cd-0404.xml
/xml/cd-0507.xml
/json/index.json
/json/cd-0403.json
/json/cd-0404.json
/json/cd-0507.json
```

So moving forward,
1. Relaton XML: define representation of a Relaton collection (as a response).
2. Define what is Relaton JSON (in JSON-LD), at least in a preliminary way. We will need this anyway in the future.
3. Make a script that generates this (or make a Jekyll hack that does this)

Notes:
1. We don't need do to server-side filtering since the indexes are not large (for now).
2. The `index` can also support pagination via a Jekyll plugin (but we don't need it yet).

**Comment by opoudjis** [comment]
They are already generated by script, from the yaml

**Comment by opoudjis** [comment]
If 1 is just a container of bibdata entries, that's trivial, and I'll do it. If there's something different to do, you'll need to define the task. 2 is indeed a separate ticket. The script is in 
https://github.com/riboseinc/relaton-server-csd

Do you have people who can do Jekyll, or should I learn it? I'd rather not do everything, but that's your call...

**Comment by opoudjis** [comment]
https://github.com/riboseinc/bib-models/issues/9

**Comment by opoudjis** [comment]
I have checked in the latest script into relaton-server-csd
