### ISSUE TITLE
Replace `system` calls

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#58]
https://github.com/riboseinc/metanorma-csd/search?q=system&unscoped_q=system

**Comment by opoudjis** [comment]
Has been addressed; the only remaining instance is the local call to asciidoctor:

`system "cd spec/examples; asciidoctor --trace -b csd -r 'metanorma-csd' rfc6350.adoc; cd ../.."`

--- and those calls are consistently there to test external calls to asciidoctor.
