### ISSUE TITLE
Release 1.0.8: contains docidentifier fix

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#60]
In pre-1.0.7, `<docidentifier>` was only the ID, but is now containing the full doc-identifier, meaning `CC/R/DS 10001:2018` rather than just `10001`. This breaks the rendering layout.

The latest commit d44968e temporarily fixes the templates to render the full `<docidentifier>` but does not fix the underlying issue. This is a release for a temporary fix (which is necessary).

**Comment by opoudjis** [comment]
@ronaldtse has debugged the generation of the identifier, and I've brought that back from isodoc into asciidoctor. I am not seeing what this breaks in rendering: there is plenty of room for the identifier in the front page. Will need more specifics on what formatting breaks with the current code.

**Comment by ronaldtse** [comment]
Yes it's all good. Thanks!
