### ISSUE TITLE
wrong documentidentifier in xml

### ISSUE THREAD

**Issue by wsdwl** [riboseinc/metanorma-csd#62]
When creating a document with adoc the header might look like this:

= CalConnect Standard: Calendar operator practices -- Guidelines to protect against calendar abuse
:title: Calendar operator practices -- Guidelines to protect against calendar abuse
:docnumber: 18003
:status: draft-standard
:doctype: report
:edition: 1
:copyright-year: 2018
:revdate: 2018-10-31T00:00:00Z
:language: en
:technical-committee: CALSPAM
:draft:
:toc:
:local-cache-only:
:data-uri-image:

 in the generated documents, this converts to 

CC/R/DS 18003:2018 in pdf
<span class="docnumber">CC/R/DS 18003:2018</span> in html

 but
<docidentifier>18003</docidentifier> in xml and 
CC/R/DS 18003:2018:2018 in doc, where it also should be CC/R/DS 18003:2018

Looks wrong to me.

**Comment by opoudjis** [comment]
Error in Word template; fixed, will release gem update.
