### ISSUE TITLE
HTML layout "example" padding on left missing

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#63]
See: https://www.calendarstandards.org/standards/csd-calspam-bcp.html

A little too close to the left border now.

<img width="595" alt="screen shot 2018-11-02 at 9 12 45 pm" src="https://user-images.githubusercontent.com/11865/47917321-16217000-dee4-11e8-80e5-c93d98cb9a92.png">

**Comment by opoudjis** [comment]
Your commit on isodoc, https://github.com/riboseinc/isodoc/commit/b735a7178a4d4f4a051982508d9d7c6371bda460, removed "padding:.75pt .75pt .75pt .75pt" from the inline styling of example_label. I'm going to put it back in, that will address it.

**Comment by opoudjis** [comment]
Making it `padding:0 0 0 1em`
