### ISSUE TITLE
Unordered list rendering broken on Chrome for some users

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#65]
Will add attachments here.

**Comment by ronaldtse** [comment]
Chrome

![chrome screenshot_2018-11-09 calconnect directive patent policy](https://user-images.githubusercontent.com/11865/48296036-301cfe80-e460-11e8-91b3-9382cb5b50e8.jpg)

Firefox

![firefox screenshot_2018-11-09 calconnect directive patent policy](https://user-images.githubusercontent.com/11865/48296037-327f5880-e460-11e8-8bcb-f6484e8e8359.png)

**Comment by opoudjis** [comment]
I am not getting this issue on my Chrome, so of course I don't know whether fixing it is going to make a difference. Is this a Windows Chrome issue?

This will impact all Metanorma HTML stylesheets that use ISO dashes as their list bullets; that means ISO and GB at least.

**Comment by opoudjis** [comment]
.... n/m, I'll just fix it: I see Pierre's CSS uses the right unicode encoding in similar contexts.

**Comment by ronaldtse** [comment]
Can you cite this issue on a new release? Thanks!

**Comment by opoudjis** [comment]
I cite all issues on new release. Which is why I've asked you to make issues for any changes you introduce...
