### ISSUE TITLE
Bugs in authoring quickstart

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#67]
I found these two typos on the authoring quickstart:

<img width="726" alt="screen shot 2018-11-22 at 12 46 33 am" src="https://user-images.githubusercontent.com/11865/48855985-36ac5e00-edf0-11e8-8de9-b2e61647e4f1.png">

**Comment by strogonoff** [comment]
aside: I’m not sure I’ll manage being documentation maintainer for each of software packages featured across RO project sites :( Considering the bus factor too, might be a good idea to arrive at a more distributed approach

**Comment by strogonoff** [comment]
removed the bug label because to me it does not seem to be a bug in metanorma-csd implementation
