### ISSUE TITLE
Add affiliation information for authors

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-csd#71]
CSD Asciidoctor currently allows information about individual authors and editors to be added as surname, givenname, role. Affiliation should be added.

**Comment by ronaldtse** [comment]
Can we make this a metanorma-standoc implementation so that all flavors can benefit from it? Thanks!

**Comment by opoudjis** [comment]
Is also required by NIST.

**Comment by ronaldtse** [comment]
For CSD, this is more of "splitting author name, role, and affiliation". We should allow taking the address as well.

Items per author:

* Full name
* Initials
* Affiliation
* Affiliation address
* URL
* Email

Maybe this should actually be "read-in" in StanDoc, and rendered in CSD (and NIST).

**Comment by opoudjis** [comment]
I have no earthly recollection what you expect this to look like in CSD, you will need to provide formatting requirements. I am gathering the information in metanorma-standoc.

**Comment by opoudjis** [comment]
For affiliation address, I never got from you an ISO 191606 spec for addresses, and I would be an idiot to require people to enter individual address fields via Asciidoctor. I am introducing into the biblio grammar a "formattedAddress" field as an alternative to a broken-down address.

**Comment by opoudjis** [comment]
Added the attributes required above to metanorma-standoc. Leaving ticket open awaiting instructions on rendering.

**Comment by ronaldtse** [comment]
I can tweak that, just render it as whatever for now; as long as the metadata is provided it’s good. Thanks!

**Comment by opoudjis** [comment]
Migrated authors and authors_affiliations metadata fields to isodoc gem.

**Comment by opoudjis** [comment]
Updated Title pages, using local roles_authors_affiliation metadata variable.
