### ISSUE TITLE
Awkward rendering of monospace phrase followed immediately by a symbol

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-csd#72]
```doc
  In this case, the server simply updates the `ORGANIZER`'s copy of the
  event based on the link clicked.
```

Gets rendered as:
```
`ORGANIZER's copy
```

If I put a space between the last backtick and the apostrophe, it renders with a space between.

**Comment by opoudjis** [comment]
https://asciidoctor.org/docs/user-manual/#unconstrained-quotes

The correct Asciidoctor for formatting within a word is to use double backtick, not single:

```doc
  In this case, the server simply updates the ``ORGANIZER``'s copy of the
  event based on the link clicked.
```

Confirmed in test doc.

**Comment by ronaldtse** [comment]
Thanks!
